### ISSUE TITLE
Optimise Lighthouse Accessibility

### ISSUE THREAD

**Issue by matthew1809** [algolia/algolia-react-boilerplate#236]
<img width="709" alt="Screenshot 2022-06-24 at 07 49 06" src="https://user-images.githubusercontent.com/10894967/175470928-66eb3813-ea24-4c7f-9d8d-05f6ec303add.png">

**Comment by nerdjfpb** [comment]
Hi @matthew1809 I tried to solve the whole thing, but sadly couldn't. 

- `Links do not have a discernible name` Doesn't show on my lighthouse. 
- `Sufficient contrast ratio` problem is hard to solve because price is using `$blue-algolia` color, only you can change that I guess. 
- `Form element` issue is coming from `react-select` couldn't find a solution for it

But I the last 2 and here the PR #242
